### ISSUE TITLE
Multiple refreshes, then blank page - no 404

### ISSUE THREAD

**Issue by PXNX** [varabyte/kobweb#87] opened 2022-01-01 19:12 UTC
When loading a url such as `http://localhost:8080/test-refresh` - which does not exist in a given project - the page continuously refreshes for some time, after which a blank page appears.

Shouldn't this instead lead to a 404 status page immediately?

**Comment by PXNX** [comment] 2022-01-01 19:12
Might be a bug aswell, seemed more like an improvement to me though ;)

**Comment by PXNX** [comment] 2022-01-01 19:23
It seemingly refreshes forever in most cases.

**Comment by bitspittle** [comment] 2022-01-02 07:45
Yes, invalid pages should 404!

**Comment by bitspittle** [comment] 2022-01-04 19:03
I'll go ahead and and change this to a "bug" label, since I am pretty sure this was working at one point but broke at some point. But otherwise yeah it would have been an enhancement :)

Labels don't really matter too much at this point, since it's not too hard to manage all the open issues at this point.

**Comment by bitspittle** [comment] 2022-01-04 19:08
I am able to reproduce this, thanks for filing. I think at some point I updated the "automatically reload when a page is recompiled" logic and must have broke this - it's getting confused and trying to reload repeatedly.

**Comment by bitspittle** [comment] 2022-01-04 19:22
Hahaha it's not at all what I expected. I have a bad regex right now for parsing the URL, and your hyphen is confusing my (bad) code.

If you type `http://localhost:8080/testrefresh` it should behave correctly.

I will fix my URL parsing logic to be more correct. I should probably delegate to the [URL](https://developer.mozilla.org/en-US/docs/Web/API/URL) class if I can and not try to reinvent the wheel.

**Comment by bitspittle** [comment] 2022-01-04 20:03
Will be fixed in kobweb 0.7.11

**Closed** 2022-01-04 20:03 UTC
Labels: bug

**Comment by PXNX** [comment] 2022-01-04 21:31
> Hahaha it's not at all what I expected. I have a bad regex right now for parsing the URL, and your hyphen is confusing my (bad) code.
> 
> If you type `http://localhost:8080/testrefresh` it should behave correctly.
> 
> I will fix my URL parsing logic to be more correct. I should probably delegate to the [URL](https://developer.mozilla.org/en-US/docs/Web/API/URL) class if I can and not try to reinvent the wheel.

Regex is wonderful😅
