### ISSUE TITLE
Export option similar to ./gradlew jsBrowserProductionWebpack

### ISSUE THREAD

**Issue by Taltus1337** [varabyte/kobweb#206] opened 2023-01-26 16:04 UTC
It would be helpful to have a simplified export option similar to ./gradlew jsBrowserProductionWebpack. So you can simply copy and paste the output to the server.

**Comment by bitspittle** [comment] 2023-01-26 20:50
Hi! Thanks for trying Kobweb!

Can you help me understand your use case more clearly?

**Comment by Taltus1337** [comment] 2023-01-26 21:40
I don't use a hoisting service I just have some webspace (from my email
domain) that I can access with FTP. The server then calls the index.html
file as the entry point. If I use compose for web and run ./gradlew
jsBrowserProductionWebpack I get all the files ready in a folder where I
can then use the index.html file to open the site offline or just copy
everything to the server.

Sorry if I miss something, but I'm really new to web development.

David Herman ***@***.***> schrieb am Do., 26. Jan. 2023,
21:50:

**Comment by bitspittle** [comment] 2023-01-27 02:04
Don't worry, I was pretty new to web development when I started this project.

Check out https://bitspittle.dev/blog/2022/staticdeploy which talks about static layouts. Maybe that will work for what you're trying to do?

**Comment by Taltus1337** [comment] 2023-01-27 04:27
Unfortunately it doesn't give me the desired result when I export kobweb
with layout static.  When I run the index.html I only get a web page
without function/navigation and the web.js is not found either.

The desired result (as with compose for web) would be that I have a fully
functional web page when I run the index.html file.

**Comment by bitspittle** [comment] 2023-01-27 05:09
I'm still not sure what your hosting situation is. Are you trying to download the index.html file locally and open it from disk?

**Comment by Taltus1337** [comment] 2023-01-27 13:50
No i try to open/execute the index.html inside .kobweb/site. (just for testing, but it is the same situation like on the server)

Using [compose for web](https://github.com/JetBrains/compose-jb/tree/master/templates/web-template) it is working fine.

**Comment by bitspittle** [comment] 2023-01-27 16:12
So when I tried to do what you were doing, I got a site that opened up correctly but wouldn't let me navigate to another page. Are you seeing that? Or something else?

The index.html fine generated by `kobweb export` is generated by `jsBrowserProductionWebpack`.

**Comment by bitspittle** [comment] 2023-01-27 16:26
Here is a video capture of me exporting my blog site (https://bitspittle.dev) (For your convenience, I skipped over about a minute of exporting)

Let's double check if you're seeing the same behavior.

https://user-images.githubusercontent.com/43705986/215138189-97a3ef89-a267-444e-b961-b6ad38661172.mp4

Note that, while this works, the second I try to navigate, it will break. This is because Kobweb navigation logic assumes you are rooted at "/" (e.g. "https://yoursite.com/" or "file://")  So in my site, if I click on the "blog" link, instead of it going from `file:///home/blah/path/whatever/index.html` to `file:///home/blah/path/whatever/blog/`, it will incorrectly go to `file:///blog`, since it has no idea where the site root is.

**Comment by Taltus1337** [comment] 2023-01-27 20:49
Ok I understand. What would you suggest in my Case?

**Comment by bitspittle** [comment] 2023-01-28 01:02
To be honest I'm still not sure 1) exactly what you're doing on your side, 2) what you're seeing, and 3) what you want to happen. 

One thing that might help: Feel free to assume I'm dumb, and give me very clear and detailed steps of what you're doing on your end. 

Finally, it's possible that Kobweb is designed to solve a different problem than the one you have. If Compose for Web is working for you, what were you hoping to get from Kobweb?

**Comment by Taltus1337** [comment] 2023-01-28 02:18
I will leave it at that because I have more or less achieved what I wanted.
I created a web preview / advertisement for my app using kobweb. Since I
didn't necessarily need javascript, it was sufficient to just use the HTML
file I created. So thanks for not making me learn HTML because of kobweb.

**Comment by bitspittle** [comment] 2023-01-28 03:45
Hahaha you're welcome.

Drop by the Discord if you ever have any further questions.

**Comment by bitspittle** [comment] 2023-03-01 01:16
(Closing as can not reproduce, apologies for never quite figuring out what was wrong in your case. Feel free to comment again later to reopen if you'd like)

**Closed by bitspittle** 2023-03-01 01:16 UTC
Labels: enhancement
