### ISSUE TITLE
Allow users to define additional scripts

### ISSUE THREAD

**Issue by dhcoder** [varabyte/kobweb#55] opened 2021-11-02 00:33 UTC
Right now, we generate an index.html but there's no way to influence which additionally scripts are included in there. We need a way to fix that, e.g. so we can depend on some existing JS library.

**Comment by bitspittle** [comment] 2021-11-19 07:19
This should be possible now that we have the @InitKobweb annotation. Something like `ctx.scripts.add(...)`

**Comment by bitspittle** [comment] 2021-12-04 07:46
Duplicate of #7 essentially

**Closed by bitspittle** 2021-12-04 07:46 UTC
Labels: enhancement
